config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#main'
  resources :products
  get 'robots' => 'products#robots', format: :text

  resources :line_items do
    put 'decrease_quantity'
    put 'increase_quantity'
  end

  get '/private_cabinate', to: 'private_cabinate#index'
  get '/private_cabinate/history_of_orders', to: 'private_cabinate#history_of_orders'
  get '/private_cabinate/history_of_views', to: 'private_cabinate#history_of_views'


  resources :carts
  resources :orders
  resources :products do
    resources :line_items
  end
  get '/products_with_offers', to: 'products#only_with_discount'
  resources :searches
  resources :shares, only: %i[show index]
  resources :categories
  resources :users
  resources :comments
  resources :ratings, only: :update
  resources :useful_articles, only: %i[show index] do
    resources :comment_posts
  end

  resource :send_message, only: %i[new create]

  get '/products/:id/delete_image', to: 'products#delete_image', as: 'delete_image'

  get '/about' => 'pages#about'
  get '/contacts' => 'pages#contacts'
  get '/delivery' => 'pages#delivery'
  get '/payment' => 'pages#payment'
  get '/partners' => 'pages#partners'
  get '/main' => 'pages#main'

  resources :products do
    get :who_bought, on: :member
  end

  namespace :admin do
    root to: 'users#index'
    resources :users do
      get :banned_user, on: :member
      put :bust_user, on: :member
      put :make_admin, on: :member
      put :make_moderator, on: :member
    end
    resources :orders do
      get :all_orders_delivered, on: :collection
      put :order_delivered, on: :member
    end
    resources :useful_articles
    resources :products do
      get :set_exchange_rates, on: :collection
      post :set_exchange_rates, to: 'products#update_products_with_exchange_rates', on: :collection
      collection { post :import }
      delete :delete_products_created_today, on: :collection
    end
    resources :categories do
      collection { post :sort }
    end
    resources :shares
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user, optional: true

  PAYMENT_TYPES = ['Оплата на банковскую Карту', 'Оплата при получении']
  DELIVERY_TYPES = ['Новая почта', 'Мист-Експресс',
                    'Маршрутка с Центрального Автовокзала г. Днепр',
                    'Самовывоз с пр-т Гагарина (р-н ТРЦ «МАТЕРИК») г. Днепр',
                    'Другие перевозчики (Просьба указать в комментарии)']
  REGIONS = []
  AREAS = []
  Ruuaby.data_path = 'db/'
  Ruuaby.load_data
  Ruuaby.countries['Украина'].each_key { |key| REGIONS << key.to_s }
  REGIONS.each { |region| Ruuaby.countries['Украина'][region].each_key { |key| AREAS << region + ' ' + key.to_s } }
  AREAS.compact.sort!

  validates :number, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  scope :last_five_orders, -> { order('created_at DESC').limit(5) }

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def order_total_price
    line_items.to_a.sum { |item| item.count_line_item_price.to_f }
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminsController
  before_action :order_resourses, only: %i[destroy order_delivered]

  def index
    @orders = Order.order(:id).paginate(page: params[:page], per_page: 50)
  end

  def destroy
    @order.destroy!
  end

  def order_delivered
    @order.update(delivered: !@order.delivered)
    OrderNotifierMailer.complete_order(@order).deliver if @order.delivered
  end

  def all_orders_delivered
    Order.all.update_all(delivered: true)
    redirect_back(fallback_location: admin_orders_path)
  end

  private

  def order_resourses
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    if @cart.line_items.empty?
      redirect_to root_url, notice: t('message.your_cart_empty')
      return
    end
    @order = Order.new
  end

  def create
    address_array = params[:order][:city]
    address_string = address_array[:area] + ', ' + address_array[:city]
    params[:order][:city] = address_string
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        @order.add_line_items_from_cart(@cart)
        @order.line_items.each do |line_item|
          line_item.update(cart_id: @cart.id)
          line_item.product.update(quantity: line_item.product.quantity - line_item.quantity)
        end
        session[:cart_id] = nil
        OrderNotifierMailer.recieved(@order).deliver
        OrderNotifierMailer.user_order_recieved(@order).deliver
        format.html { redirect_to root_url, notice: t('message.order_in_treatment') }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :number, :comment, :city,
                                  :post_office_number, :pay_type, :way_delivery, :user_id)
  end
end

app/views/admin/orders/_order_show.html.erb
<div class="modal fade order_view_<%= order.id %>" id="order_view_<%= order.id %>" tabindex="-1" role="dialog" aria-labelledby="order_view_<%= order.id  %>" aria-hidden="true"">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
        <h2 class="modal-title">Заказ №<%= order.id %></h2>
      </div>
      <div class="modal-body container">
        <div class="row">
          <div class="col-md-9 col-xs-12">
            <p><b>Имя: </b><%= order.full_name %></p>
            <p><b>Номер телефона: </b><%= order.number %></p></p>
            <p><b>Почтовый адрес: </b><%= order.email %></p></p>
            <p><b>Город: </b><%= order.city %></p>
            <p><b>Способ доставки: </b><%= order.way_delivery %></p>
            <p><b>Номер почтового отделения: </b><%= order.post_office_number %></p>
            <p><b>Способ оплаты: </b><%= order.pay_type %></p>
            <p>
              <b>Комментарий: </b>
              <p><%= raw order.comment %></p>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-9 col-xs-12">
            <table class="table-hover table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Наименование</th>
                  <th>Код</th>
                  <th>Категория</th>
                  <th>Цена</th>
                  <th>Кол-во</th>
                  <th>Сумма</th>
                </tr>
              </thead>
              <tbody>
                <% order.line_items.each_with_index do |line_item, i| %>
                  <tr>
                    <td><%= i+1 %></p>
                    <td><%= line_item.product.full_name_product %></p>
                    <td><%= line_item.product.product_code %></p>
                    <td><%= line_item.product.category.name %></p>
                    <td><%= line_item.price_discount %></p>
                    <td><%= line_item.quantity %></p>
                    <td><%= line_item.count_line_item_price %></p>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-6">
            <h2>Сумма покупок: <%= number_to_currency(order.order_total_price, unit: "₴") %></h2>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/destroy.js.erb
$('#order_<%= @order.id %>').remove();

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to "Подтвердить все заказы", all_orders_delivered_admin_orders_path, class: 'btn btn-sm btn-primary pull-right' %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <td>#</td>
        <td>Имя</td>
        <td>Номер телефона</td>
        <td>Город</td>
        <td>Способ получения</td>
        <td>Способ оплаты</td>
        <td>Действия</td>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr id="order_<%= order.id %>" class="<%= 'bg-success' if order.delivered %>">
            <td><%= order.id %></td>
            <td><%= order.full_name %></td>
            <td><%= order.number %></td></td>
            <td><%= order.city %></td>
            <td><%= order.way_delivery %></td>
            <td><%= order.pay_type %></td>
            <td>
              <a href="#order_view_<%= order.id  %>" class='btn btn-sm btn-info' data-toggle="modal" data-target="#order_view_<%= order.id %>">Просмотр</a>
              <%= link_to "#{ order.delivered ? 'Отменить подтверждение заказа' : 'Подтвердить успешный заказ' }", order_delivered_admin_order_path(order), remote: true, data: { url: admin_orders_path(id: order.id), method: :put }, class: 'btn btn-sm btn-primary', id: "delivered_#{order.id}" %>
              <%= link_to 'Удалить', admin_order_path(order), method: :delete, remote: true, data: { confirm: "Вы действительно хотите  удалить  этот заказ?" }, class: 'btn btn-sm btn-danger'%>
              <%= render 'order_show', order: order %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <center>
    <%= will_paginate @orders, renderer: BootstrapPagination::Rails, previous_label: '<=', next_label:'=>' %>
  </center>
</div>

app/views/admin/orders/order_delivered.js.erb
$('#order_<%= @order.id %>').toggleClass('bg-success');
$("#delivered_<%= @order.id %>").text(function(i, text){
  return text === "Подтвердить успешный заказ" ? "Отменить подтверждение заказа": "Подтвердить успешный заказ";
})