config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#main'
  resources :products
  get 'robots' => 'products#robots', format: :text

  resources :line_items do
    put 'decrease_quantity'
    put 'increase_quantity'
  end

  get '/private_cabinate', to: 'private_cabinate#index'
  get '/private_cabinate/history_of_orders', to: 'private_cabinate#history_of_orders'
  get '/private_cabinate/history_of_views', to: 'private_cabinate#history_of_views'


  resources :carts
  resources :orders
  resources :products do
    resources :line_items
  end
  get '/products_with_offers', to: 'products#only_with_discount'
  resources :searches
  resources :shares, only: %i[show index]
  resources :categories
  resources :users
  resources :comments
  resources :ratings, only: :update
  resources :useful_articles, only: %i[show index] do
    resources :comment_posts
  end

  resource :send_message, only: %i[new create]

  get '/products/:id/delete_image', to: 'products#delete_image', as: 'delete_image'

  get '/about' => 'pages#about'
  get '/contacts' => 'pages#contacts'
  get '/delivery' => 'pages#delivery'
  get '/payment' => 'pages#payment'
  get '/partners' => 'pages#partners'
  get '/main' => 'pages#main'

  resources :products do
    get :who_bought, on: :member
  end

  namespace :admin do
    root to: 'users#index'
    resources :users do
      get :banned_user, on: :member
      put :bust_user, on: :member
      put :make_admin, on: :member
      put :make_moderator, on: :member
    end
    resources :orders do
      get :all_orders_delivered, on: :collection
      put :order_delivered, on: :member
    end
    resources :useful_articles
    resources :products do
      get :set_exchange_rates, on: :collection
      post :set_exchange_rates, to: 'products#update_products_with_exchange_rates', on: :collection
      collection { post :import }
      delete :delete_products_created_today, on: :collection
    end
    resources :categories do
      collection { post :sort }
    end
    resources :shares
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/useful_article.rb
class UsefulArticle < ApplicationRecord
  belongs_to :category_post
  belongs_to :user, optional: true
  has_many :comment_posts, dependent: :destroy

  mount_uploader :preview, PreviewUploader

  scope :only_published, -> { where(published: true) }

  self.per_page = 10
end

app/controllers/admin/useful_articles_controller.rb
class Admin::UsefulArticlesController < AdminsController
  before_action :article_resource, only: %i[edit update destroy]

  def index
    @useful_articles = UsefulArticle.order(:id).paginate(page: params[:page], per_page: 20)
  end

  def new
    @useful_article = UsefulArticle.new
  end

  def create
    @useful_article = UsefulArticle.create(articles_params)
    if @useful_article.save
      redirect_to admin_useful_articles_path, notice: 'Новая статья добавлена'
    else
      render :new
    end
  end

  def update
    if @useful_article.update(articles_params)
      redirect_to admin_useful_articles_path, notice: 'Статья была успешно обновлена'
    else
      render :edit
    end
  end

  def destroy
    @useful_article.destroy!
    redirect_to admin_useful_articles_path, notice: 'Статья удалена'
  end

  private

  def article_resource
    @useful_article = UsefulArticle.find(params[:id])
  end

  def articles_params
    params.require(:useful_article).permit(:title, :body, :preview, :user_id, :published, :category_post_id)
  end
end

app/controllers/useful_articles_controller.rb
class UsefulArticlesController < ApplicationController
  def index
    @useful_articles = UsefulArticle.only_published.page(params[:page])
  end

  def show
    @useful_article = UsefulArticle.find(params[:id])
    @comment_posts = @useful_article.comment_posts.page(params[:page])
  end
end

app/helpers/useful_articles_helper.rb
module UsefulArticlesHelper
  def count_comments
    comment_count = @useful_article.comment_posts.count
    last_int = comment_count.to_s.chars.last(1).join.to_i
    if last_int == 1
      "#{comment_count} комментарий"
    elsif last_int >= 2 && last_int <= 4
      "#{comment_count} комментария"
    elsif comment_count == 0
      'На данный момент отсутствуют комментарии для этого поста'
    else
      "#{comment_count} комментариев"
    end
  end
end

app/views/admin/useful_articles/_form.html.erb
<%= form_for [:admin, @useful_article] do |f| %>
  <%= f.label 'Введите заголовок' %>
  <br>
  <%= f.text_field :title, placeholder: "Введите заголовок", class: 'form-control', required: true %>
  <br>
  <%= f.select :category_post_id, options_from_collection_for_select(CategoryPost.all, :id, :name), {}, class: 'form-control' %>
  <br>
    <%= f.label(:published, "Публикация") %>
    <%= f.check_box :published %>
  <hr>
  <%= f.label 'Содержание' %>
  <%= f.hidden_field  :user_id, value: current_user.id %>
  <br>
  <%= f.cktext_area :body, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' }, placeholder: "Введите заголовок", required: true %>
  <br>
  <%= f.file_field :preview %>
  <br>
  <%= f.submit class: 'btn btn-success pull-left' %>
  <%= link_to 'Назад к статьям', admin_useful_articles_path, class: 'btn btn-primary pull-right' %>
  <p>
<% end %>

app/views/admin/useful_articles/edit.html.erb
<h1>Редактивировать статью</h1>
<div class="col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/admin/useful_articles/index.html.erb
<h1>Полезные статьи</h1>
<div class="col-md-12 col-xs-12">
  <%= link_to 'Новая статья', new_admin_useful_article_path %>
  <br>
  <table class="table table-hover">
    <thead>
      <tr class='info'>
        <td>#</td>
        <td width="35%">Заголовок</td>
        <td width="60px">Изображение</td>
        <td width="200px">Дата публикации</td>
        <td>Категория</td>
        <td>Опубликовано</td>
        <td>Действия</td>
      </tr>
    </thead>
    <tbody>
      <% @useful_articles.each_with_index do |u_a, i| %>
        <tr>
          <td><%= u_a.id %></td>
          <td><%= link_to u_a.title, useful_article_path(u_a), target: '_blank' %></td>
          <td><%= image_tag u_a.preview_url(:thumbnail), class: 'thumbnail useful_articles_image_index' %></td>
          <td><%= u_a.created_at.strftime("%B %dth, %Y") %></td>
          <td><%= u_a.category_post.name %></td>
          <td>
            <% if u_a.published %>
              <%= fa_icon 'check-square-o', class: 'text-success fa-2x' %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Редактивировать', edit_admin_useful_article_path(u_a), class: 'btn btn-sm btn-warning' %> |
            <%= link_to 'Удалить', admin_useful_article_path(u_a), method: :delete, data: { confirm: "Вы действительно хотите удалить статью № #{ i+1 }" }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row">
  <center>
    <%= will_paginate @useful_articles, renderer: BootstrapPagination::Rails, previous_label: '<=', next_label:'=>' %>
  </center>
</div>

app/views/admin/useful_articles/new.html.erb
<h1>Новая статья</h1>
<div class="col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>