config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#main'
  resources :products
  get 'robots' => 'products#robots', format: :text

  resources :line_items do
    put 'decrease_quantity'
    put 'increase_quantity'
  end

  get '/private_cabinate', to: 'private_cabinate#index'
  get '/private_cabinate/history_of_orders', to: 'private_cabinate#history_of_orders'
  get '/private_cabinate/history_of_views', to: 'private_cabinate#history_of_views'


  resources :carts
  resources :orders
  resources :products do
    resources :line_items
  end
  get '/products_with_offers', to: 'products#only_with_discount'
  resources :searches
  resources :shares, only: %i[show index]
  resources :categories
  resources :users
  resources :comments
  resources :ratings, only: :update
  resources :useful_articles, only: %i[show index] do
    resources :comment_posts
  end

  resource :send_message, only: %i[new create]

  get '/products/:id/delete_image', to: 'products#delete_image', as: 'delete_image'

  get '/about' => 'pages#about'
  get '/contacts' => 'pages#contacts'
  get '/delivery' => 'pages#delivery'
  get '/payment' => 'pages#payment'
  get '/partners' => 'pages#partners'
  get '/main' => 'pages#main'

  resources :products do
    get :who_bought, on: :member
  end

  namespace :admin do
    root to: 'users#index'
    resources :users do
      get :banned_user, on: :member
      put :bust_user, on: :member
      put :make_admin, on: :member
      put :make_moderator, on: :member
    end
    resources :orders do
      get :all_orders_delivered, on: :collection
      put :order_delivered, on: :member
    end
    resources :useful_articles
    resources :products do
      get :set_exchange_rates, on: :collection
      post :set_exchange_rates, to: 'products#update_products_with_exchange_rates', on: :collection
      collection { post :import }
      delete :delete_products_created_today, on: :collection
    end
    resources :categories do
      collection { post :sort }
    end
    resources :shares
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/shared/_button_mobile.html.erb
<!-- This is the container enabling the JavaScript -->
<div class="uk-button-dropdown searsces" data-uk-dropdown="{justify:'.mobile'}">
  <button class="mobile_search_button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
  <div class="uk-dropdown searsces">
    <%= render "searches/new" %>
  </div>
</div>
<div class="uk-button-dropdown" data-uk-dropdown="{justify:'.mobile'}">
  <button class="mobile_category_button categories"><span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span></button>
  <div class="uk-dropdown categories">
    <%= render "categories/sidebar_category_mobile" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-wrap">
    <div class="footer__subscribe-wrap">
      <div class="footer-subscribe">
        <button class='btn btn-primary' data-toggle="modal" data-target="#form_send">
          <%= t "contact_form.contact_with_us" %>
        </button>
        <p></p>
        <%= render 'shared/modal_send_form' %>
      </div>
      <div class="header__phone">
        <br>
        <div class="phone-numbers">
          <div class="row">
            <div class="col-xs-2 col-md-2">
              <%= fa_icon 'phone', class: 'fa-3x phone-icon' %>
            </div>
            <div class="col-xs-10 col-md-10">
              <p class="numbers">095-775-16-86</p>
              <p class="numbers">068-682-99-19</p>
              <p class='numbers'><i>с 9:00 - 21:00</i></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer__layout">
      <div class="footer__columns-wrap">
        <div class="footer__columns">
          <ul class="footer-list">
            <p></p>
            <% Category.only_parent.limit(8).each do |category| %>
              <%= link_to category_path(category) do %>
                <li class="footer-list__item"><%= truncate(category.name, length: 20, title: "#{category.name}") %></li>
              <% end %>
            <% end %>
          </ul>
          <ul class="footer-list">
            <li class="footer-list__item"><%= link_to t("header_menu.products"), products_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.payment"), payment_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.delivery"), delivery_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.useful_article"), useful_articles_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.offers"), shares_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.reviews"), comments_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.contact"), contacts_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.about"), about_path %></li>
            <li class="footer-list__item"><%= link_to t("header_menu.partner"), partners_path %></li>
          </ul>
        </div>
        <div class="footer-copyright">
          <%= link_to root_path do %>
            <%= cl_image_tag("мапапама_nb3pbw.png", :quality=>15, :height=>40, :crop=>"scale") %>
            <%= cl_image_tag("logo.png", :quality=>15, :width=>40, :crop=>"scale") %>
          <% end %>
          <p>
            <%= raw t "leuze" %>
            <% 3.times do %>
              <%= fa_icon 'check', class: 'fa-x2 check-green' %>
            <% end %>
          </p>
        </div>
        <div class="footer-text"><%= date_of_existence %></div>
        <div class="social-button">
          <a href="https://www.facebook.com/mapapamacomua-1706468629401662/" target='_blank' class="fa fa-icons fa-facebook"></a>
          <a href="https://www.instagram.com/mapapama.com.ua/" target='_blank' class="fa fa-icons fa-instagram"></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header_menu.html.erb
<div class="row header-menu-button-xs">
  <div class="col-xs-12 col-md-12">
    <br>
    <button id="header-menu-button-toggle" class='btn btn-default pull-right'>
      <%= fa_icon 'bars', class: 'fa-2x button-toggle-menu' %>
    </button>
  </div>
</div>
<div class="row header-menu-items">
  <div class="col-md-12 col-xs-12">
    <%= tag.div class: 'top_nav sticky' do %>
      <%= link_to t("header_menu.main"), root_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.products"), products_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.payment"), payment_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.delivery"), delivery_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.useful_article"), useful_articles_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.offers"), shares_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.reviews"), comments_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.contact"), contacts_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.about"), about_path, class: 'top_nav_button' %>
      <%= link_to t("header_menu.partner"), partners_path, class: 'top_nav_button' %>
    <% end %>
  </div>
</div>

app/views/shared/_header_one.html.erb
<div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 top_container_left">
  <div class="row">
    <div class="col-md-5 col-lg-5 col-xs-9 col-sm-4 mapapama_logo">
      <%= link_to root_path do %>
        <%= cl_image_tag("мапапама_nb3pbw.png", quality: 15, height: 100, crop: "scale") %>
      <% end %>
    </div>
    <div class="col-md-2 col-lg-2 col-xs-3 col-sm-2 mapapama_logo">
      <%= link_to root_path do %>
        <%= cl_image_tag("logo.png", quality: 15, width: 84, crop: "scale") %>
      <% end %>
    </div>
    <div class="col-md-5 col-lg-5 col-xs-12 col-sm-6 leuze">
      <%= raw t "leuze" %>
      <% 1.times do %>
        <%= fa_icon 'check', class: 'fa-1x check-green' %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 top_container_center">
  <div class="row">
    <div class="phone-numbers">
      <div class="row">
        <div class="col-xs-12 col-md-10 col-sm-12">
          <p class="numbers col-xs-12 col-md-12 col-sm-8"><%= fa_icon 'phone', class: 'fa-1x phone-icon', text: '095-775-16-86; 068-682-99-19' %></p>
          <p class='numbers col-xs-12 col-md-12 col-sm-4'><i>с 9:00 - 21:00</i></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-xs-12 col-sm-6 top_container_right">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12 col-sm-12">
      <div class="col-md-8 col-xs-7 col-sm-6">
        <% if user_signed_in? %>
          <div class="dropdown">
            <button class="dropdown-toggle pull-left" type="button" data-toggle="dropdown">
              <span class="full-name-header">
                <%= current_user.full_name %>
              </span>
              <%= image_tag current_user.avatar_url(:small), class: 'img-circle header-avatar' %>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to t("header_one.my_profile"), private_cabinate_path %></li>
              <% if current_user.admin? or current_user.moderator? %>
                <li><%= link_to 'Панель управления', admin_root_path %></li>
              <% end %>
              <li class='divider'></li>
              <li><%= link_to t("header_one.log_out"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <%= link_to t("header_one.sign_up"), new_user_registration_path %>
          |
          <%= link_to t("header_one.log_in"), new_user_session_path %>
        <% end %>
      </div>
      <div class="col-md-4 col-xs-5 col-sm-6">
        <div class="btn-group pull-right">
          <%= link_to cart_path(@cart.id), class: "btn btn-success btn-sm" do %>
            <%= fa_icon 'shopping-basket' %>
          <% end %>
          <button class='btn btn-sm btn-primary' data-toggle="modal" data-target="#form_send">
            <%= fa_icon 'envelope-o' %>
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12 col-sm-12">
      <%= form_tag(products_path, method: :get) do %>
        <span class="input-group">
          <%= text_field_tag :query, nil, placeholder: t("header_one.search_placeholder"), required: true, class: 'form-control search-input' %>
          <span class="input-group-btn">
            <%= submit_tag t("header_one.search"), query: nil, class: "btn btn-default"  %>
          </span>
        </span>
      <% end %>
      <div class="row">
        <div class="col-md-8 col-xs-5 col-sm-6">
          <%= link_to_unless_current 'RU', locale: 'ru' %> |
          <%= link_to_unless_current 'UA', locale: 'ua' %> |
          <%= link_to_unless_current 'EN', locale: 'en' %>
        </div>
        <div class="social-button col-md-4 col-xs-7 col-sm-6">
          <div class="pull-right">
            <a href="https://www.facebook.com/mapapamacomua-1706468629401662/" target='_blank' class="fa fa-icons fa-facebook"></a>
            <a href="https://www.instagram.com/mapapama.com.ua/" target='_blank' class="fa fa-icons fa-instagram"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_send_form.html.erb
<div class="modal fade" id="form_send" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
          <%= t 'contact_form.contact_with_us' %>
        </h4>
      </div>
      <%= render 'send_messages/new' %>
    </div>
  </div>
</div>

app/views/shared/_social_link.html.erb
<ul id="social_side_links">
  <li>
    <a style="background-color: #4c75a3;" href="https://vk.com" target="_blank">
      <img src="https://vignette2.wikia.nocookie.net/risen/images/4/4a/VK_%D0%B8%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0.png/revision/latest?cb=20130307133156&path-prefix=ru" alt="" />
    </a>
  </li>
  <li>
    <a style="background-color: #3c5a96;" href="https://facebook.com" target="_blank">
      <img src="https://www.dropbox.com/s/xk5pdj8nks1ymdh/facebook-icon.png?raw=1" alt="" />
    </a>
  </li>
  <li>
    <a style="background-color: red;" href="https://google.com" target="_blank">
      <img src="http://www.yourvillageonline.com/wp-content/uploads/2015/11/google-plus-icon.png" alt="" />
    </a>
  </li>
</ul>

app/views/shared/_sorting_parametrs.html.erb
<li><%= link_to t('products.sort.first_cheap'), sort: 'price', order_type: 'ASC' %></li>
<li><%= link_to t('products.sort.first_expensive'), sort: 'price', order_type: 'DESC' %></li>
<li><%= link_to t('products.sort.first_new'), sort: 'created_at', order_type: 'ASC' %></li>
<li><%= link_to t('products.sort.first_old'), sort: 'created_at', order_type: 'DESC' %></li>
<li><%= link_to t('products.sort.first_with_offer'), sort: 'discount', order_type: 'DESC' %></li>