config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#main'
  resources :products
  get 'robots' => 'products#robots', format: :text

  resources :line_items do
    put 'decrease_quantity'
    put 'increase_quantity'
  end

  get '/private_cabinate', to: 'private_cabinate#index'
  get '/private_cabinate/history_of_orders', to: 'private_cabinate#history_of_orders'
  get '/private_cabinate/history_of_views', to: 'private_cabinate#history_of_views'


  resources :carts
  resources :orders
  resources :products do
    resources :line_items
  end
  get '/products_with_offers', to: 'products#only_with_discount'
  resources :searches
  resources :shares, only: %i[show index]
  resources :categories
  resources :users
  resources :comments
  resources :ratings, only: :update
  resources :useful_articles, only: %i[show index] do
    resources :comment_posts
  end

  resource :send_message, only: %i[new create]

  get '/products/:id/delete_image', to: 'products#delete_image', as: 'delete_image'

  get '/about' => 'pages#about'
  get '/contacts' => 'pages#contacts'
  get '/delivery' => 'pages#delivery'
  get '/payment' => 'pages#payment'
  get '/partners' => 'pages#partners'
  get '/main' => 'pages#main'

  resources :products do
    get :who_bought, on: :member
  end

  namespace :admin do
    root to: 'users#index'
    resources :users do
      get :banned_user, on: :member
      put :bust_user, on: :member
      put :make_admin, on: :member
      put :make_moderator, on: :member
    end
    resources :orders do
      get :all_orders_delivered, on: :collection
      put :order_delivered, on: :member
    end
    resources :useful_articles
    resources :products do
      get :set_exchange_rates, on: :collection
      post :set_exchange_rates, to: 'products#update_products_with_exchange_rates', on: :collection
      collection { post :import }
      delete :delete_products_created_today, on: :collection
    end
    resources :categories do
      collection { post :sort }
    end
    resources :shares
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/private_cabinate_controller.rb
class PrivateCabinateController < ApplicationController
  before_action :require_user
  before_action :user_resource

  def index
  end

  def history_of_orders
    @user_olders = @user.orders.order('id DESC').paginate(page: params[:page], per_page: 20)
  end

  def history_of_views
    @user_views = @user.user_views.order('id DESC').limit(10)
  end

  private

  def user_resource
    @user = User.find(current_user.id)
  end
end

app/helpers/private_cabinate_helper.rb
module PrivateCabinateHelper
end

app/views/private_cabinate/_menu.html.erb
<%= link_to 'Мой профиль', private_cabinate_path, class: 'list-group-item' %>
<%= link_to 'История заказов', private_cabinate_history_of_orders_path, class: 'list-group-item' %>
<%= link_to 'История просмотров', private_cabinate_history_of_views_path, class: 'list-group-item' %>

app/views/private_cabinate/history_of_orders.html.erb
<h1>История заказов</h1>
<div class="row">
  <div class="col-md-3 col-xs-12">
    <div class="list-group">
      <%= render 'menu' %>
    </div>
  </div>
  <div class="col-md-9 col-xs-12">
    <div class="well">
      <h2><%= t('profile.your_orders.title') %></h2>
      <table class='table'>
        <thead>
          <th>#</th>
          <th><%= t('profile.your_orders.total_sum') %></th>
          <th><center><%= t('profile.your_orders.stat') %></center></th>
        </thead>
        <tbody>
          <% @user_olders.each_with_index do |user_older, i| %>
            <tr>
              <td><%= user_older.id %></td>
              <td><%= number_to_currency(user_older.order_total_price, locale: :ru) %></td>
              <td>
                <center>
                  <%= fa_icon "#{ user_older.delivered ? 'check' : 'minus' }-square-o", class: "text-#{user_older.delivered ? 'success' : 'warning' } fa-2x", title: "#{ user_older.delivered ? t('profile.your_orders.status.success') : t('profile.your_orders.status.expect') }" %>
                </center>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <center>
        <%= will_paginate @user_olders, renderer: BootstrapPagination::Rails, previous_label: '<=', next_label:'=>' %>
      </center>
    </div>
  </div>
</div>

app/views/private_cabinate/history_of_views.html.erb
<h1>История просмотров</h1>
<div class="row">
  <div class="col-md-3 col-xs-12">
    <div class="list-group">
      <%= render 'menu' %>
    </div>
  </div>
  <div class="col-md-9 col-xs-12">
    <div class="well">
      <% if @user_views != 0 %>
        <div class="row">
          <div class="col-md-12">
            <% @user_views.each do |view| %>
              <div class="col-md-3 col-sm-4 col-xs-6 product_view_class product_view_class_all" >
                <%= render  partial: "products/product", locals: { product: view.product } %>
                <%= button_to t('products.add_to_cart'), product_line_items_path(view.product.id), class: "buttom_add_to_cart", remote: true %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/private_cabinate/index.html.erb
<h1>Профиль пользователя</h1>
<div class="row">
  <div class="col-md-3 col-xs-12">
    <div class="list-group">
      <%= render 'menu' %>
    </div>
  </div>
  <div class="col-md-9 col-xs-12">
    <div class="well">
      <h3>
        <%= @user.full_name %>
        <% if current_user.id == @user.id %>
          <%= link_to edit_user_registration_path(@user) do %>
            <%= fa_icon 'pencil', title: t('profile.edit_profile') %>
          <% end %>
        <% end %>
      </h3>
      <div class="row">
        <div class="col-md-2 col-xs-3">
          <%= image_tag @user.avatar_url(:medium), class: 'img-thumbnail profile-avatar' %>
        </div>
        <div class="col-md-10 col-xs-9">
          <p>
            <strong><%= t('profile.email') %></strong>
            <%= @user.email %>
          </p>
          <p>
            <strong><%= t('profile.number_phone') %></strong>
            <%= @user.number %>
          </p>
          <p>
            <strong><%= t('profile.role') %></strong>
            <% if @user.admin? %>
              <span class="label label-danger"><%= t('profile.admin') %></span>
            <% elsif @user.moderator? %>
              <span class="label label-warning">Модератор</span>
            <% else %>
              <span class="label label-primary"><%= t('profile.user') %></span>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>